version: "3.9"  # optional since v1.27.0
services:
  serveractionbackup:
    build: .
    ports:
      - "5000:5000"
    image: serveractionbackup:2.0
    restart: always
    volumes: 
      - /mnt/d/odoo_code:/app/data
#       - server-action:/app

# volumes:
#   server-action:
